name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          # Note that we assume the following things about the build tests here:
          #   1. Every directory in `build_test` is a project managed with yarn
          #   2. All these projects store their cache in `<project>/.yarn/cache`
          # It's not that robust, but should be sufficient for us for now.
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/build_tests/*/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn typecheck
      - run: yarn lint:all --max-warnings 0
      - run: yarn test
      - name: Publish theatre packages to the local registry
        run: npx zx ./scripts/publish-to-yalc.mjs
      - name: Install the dependencies of the build test projects
        run: npx zx ./scripts/build-tests/install-dependencies.mjs
      - name: Add the theatre packages to the build test projects
        run: npx zx ./scripts/build-tests/link-theatre-packages.mjs
      - name: Run the build tests
        run: npx zx ./scripts/build-tests/build-projects.mjs
      - name: Download playwright
        run: yarn workspace playground run playwright install
      - name: Run e2e tests with percy
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: 'yarn test:e2e:ci'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
